<?php

namespace Database\Seeders;

use App\Models\Location;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LocationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $locations = [
            'Aborlan, Palawan',
            'Abra de Ilog, Occidental Mindoro',
            'Abucay, Bataan',
            'Abulug, Cagayan',
            'Abuyog, Leyte',
            'Adams, Ilocos Norte',
            'Agdangan, Quezon',
            'Aglipay, Quirino',
            'Agno, Pangasinan',
            'Agoncillo, Batangas',
            'Agoo, La Union',
            'Aguilar, Pangasinan',
            'Aguinaldo, Ifugao',
            'Agutaya, Palawan',
            'Ajuy, Iloilo',
            'Alabat, Quezon',
            'Alabel (Capital), Sarangani',
            'Alamada, North Cotabato',
            'Alaminos City, Pangasinan',
            'Alaminos, Laguna',
            'Alangalang, Leyte',
            'Albuera, Leyte',
            'Albuquerque, Bohol',
            'Alcala, Cagayan',
            'Alcala, Pangasinan',
            'Alcantara, Cebu',
            'Alcantara, Romblon',
            'Alcoy, Cebu',
            'Alegria, Cebu',
            'Alegria, Surigao Del Norte',
            'Aleosan, North Cotabato',
            'Alfonso Lista (Potia), Ifugao',
            'Alfonso, Cavite',
            'Aliaga, Nueva Ecija',
            'Alicia, Bohol',
            'Alicia, Isabela',
            'Alicia, Zamboanga Sibugay',
            'Alilem, Ilocos Sur',
            'Alimodian, Iloilo',
            'Alitagtag, Batangas',
            'Allacapan, Cagayan',
            'Allen, Northern Samar',
            'Almagro, Western Samar',
            'Almeria, Biliran',
            ' Aloguinsa, Cebu',
            'Aloran, Misamis Occidental',
            'Altavas, Aklan',
            'Alubijid, Misamis Oriental',
            'Amadeo, Cavite',
            'Ambaguio, Nueva Vizcaya',
            'Amlan (Ayuquitan), Negros Oriental',
            'Ampatuan, Maguindanao',
            'Amulung, Cagayan',
            'Anahawan, Southern Leyte',
            'Anao, Tarlac',
            'Anda, Bohol',
            'Anda, Pangasinan',
            'Angadanan, Isabela',
            'Angat, Bulacan',
            'Angeles City, Pampanga',
            'Angono, Rizal',
            'Anilao, Iloilo',
            'Anini-Y, Antique',
            'Antequera, Bohol',
            'Antipas, North Cotabato',
            'Antipolo City, Rizal',
            'Apalit, Pampanga',
            'Aparri, Cagayan',
            'Araceli, Palawan',
            'Arakan, North Cotabato',
            'Arayat, Pampanga',
            'Argao, Cebu',
            'Aringay, La Union',
            'Aritao, Nueva Vizcaya',
            'Aroroy, Masbate',
            'Arteche, Eastern Samar',
            'Asingan, Pangasinan',
            'Asipulo, Ifugao',
            'Asturias, Cebu',
            'Asuncion (Saug), Davao Del Norte',
            'Atimonan, Quezon',
            'Atok, Benguet',
            'Aurora, Isabela',
            'Aurora, Zamboanga Del Sur',
            'Ayugon, Negros Oriental',
            'Baao, Camarines Sur',
            ' Baay-Licuan (Licuan), Abra',
            'Babatngon, Leyte',
            'Bacacay, Albay',
            'Bacarra, Ilocos Norte',
            'Baclayon, Bohol',
            'Bacnotan, La Union',
            'Baco, Oriental Mindoro',
            'Bacolod City, Negros Occidental',
            'Bacolod, Lanao Del Norte',
            'Bacolor, Pampanga',
            'Bacong, Negros Oriental',
            'Bacoor, Cavite',
            'Bacuag, Surigao Del Norte',
            'Bacungan, Zamboanga Del Norte',
            'Badian, Cebu',
            'Badiangan, Iloilo',
            'Badoc, Ilocos Norte',
            'Bagabag, Nueva Vizcaya',
            'Bagac, Bataan',
            'Bagamanoc, Catanduanes',
            'Baganga, Davao Oriental',
            'Baggao, Cagayan',
            'Bago City, Negros Occidental',
            'Baguio City, Benguet',
            'Bagulin, La Union',
            'Bagumbayan, Sultan Kudarat',
            'Bakun, Benguet',
            'Balabac, Palawan',
            'Balagtas (Bigaa), Bulacan',
            'Balamban, Cebu',
            'Balanga City, Bataan',
            'Balangiga, Eastern Samar',
            'Balangkayan, Eastern Samar',
            'Balaoan, La Union',
            'Balasan, Iloilo',
            'Balatan, Camarines Sur',
            'Balayan, Batangas',
            'Balbalan, Kalinga',
            'Baleno, Masbate',
            'Balete, Aklan',
            'Balete, Batangas',
            ' Baliangao, Misamis Occidental',
            'Baliguian, Zamboanga Del Norte',
            'Balilihan, Bohol',
            'Balingasag, Misamis Oriental',
            'Balingoan, Misamis Oriental',
            'Baliuag, Bulacan',
            'Ballesteros, Cagayan',
            'Baloi, Lanao Del Norte',
            'Balud, Masbate',
            'Balungao, Pangasinan',
            'Bamban, Tarlac',
            'Bambang, Nueva Vizcaya',
            'Banate, Iloilo',
            'Banaue, Ifugao',
            'Banaybanay, Davao Oriental',
            'Banayoyo, Ilocos Sur',
            'Banga, Aklan',
            'Banga, South Cotabato',
            'Bangar, La Union',
            'Bangued, Abra',
            'Bangui, Ilocos Norte',
            'Bani, Pangasinan',
            'Banisilan, North Cotabato',
            'Banna (Espiritu), Ilocos Norte',
            'Bansalan, Davao Del Sur',
            'Bansud, Oriental Mindoro',
            'Bantay, Ilocos Sur',
            'Bantayan, Cebu',
            'Banton, Romblon',
            'Baras, Catanduanes',
            'Baras, Rizal',
            'Barbaza, Antique',
            'Barili, Cebu',
            'Barira, Maguindanao',
            'Barlig, Mountain Province',
            'Barobo, Surigao Del Sur',
            'Barotac Nuevo, Iloilo',
            'Barotac Viejo, Iloilo',
            'Baroy, Lanao Del Norte',
            'Barugo, Leyte',
            'Basay, Negros Oriental',
            ' Basco, Batanes',
            'Basey, Western Samar',
            'Basilisa (Rizal), Surigao Del Norte',
            'Basista, Pangasinan',
            'Basud, Camarines Norte',
            'Batac, Ilocos Norte',
            'Batad, Iloilo',
            'Batan, Aklan',
            'Batangas City, Batangas',
            'Bataraza, Palawan',
            'Bato, Camarines Sur',
            'Bato, Catanduanes',
            'Bato, Leyte',
            'Batuan, Bohol',
            'Batuan, Masbate',
            'Bauan, Batangas',
            'Bauang, La Union',
            'Bauko, Mountain Province',
            'Baungon, Bukidnon',
            'Bautista, Pangasinan',
            'Bay, Laguna',
            'Bayabas, Surigao Del Sur',
            'Bayambang, Pangasinan',
            'Bayawan City (Tulong), Negros Oriental',
            'Baybay, Leyte',
            'Bayog, Zamboanga Del Sur',
            'Bayombong, Nueva Vizcaya',
            'Bayugan, Agusan Del Sur',
            'Belison, Antique',
            'Benito Soliven, Isabela',
            'Besao, Mountain Province',
            'Bien Unido, Bohol',
            'Bilar, Bohol',
            'Biliran, Biliran',
            'Binalbagan, Negros Occidental',
            'Binalonan, Pangasinan',
            'Binan, Laguna',
            'Binangonan, Rizal',
            'Bindoy (Payabon), Negros Oriental',
            'Bingawan, Iloilo',
            'Binidayan, Lanao Del Sur',
            'Binmaley, Pangasinan',
            'Binuangan, Misamis Oriental',
            'Biri, Northern Samar',
            'Bislig City, Surigao Del Sur',
            'Boac, Marinduque',
            'Bobon, Northern Samar',
            'Bocaue, Bulacan',
            'Bogo, Cebu',
            'Bokod, Benguet',
            'Bolinao, Pangasinan',
            'Boliney, Abra',
            'Boljoon, Cebu',
            'Bongabon, Nueva Ecija',
            'Bongabong, Oriental Mindoro',
            'Bongao, Tawi-tawi',
            'Bonifacio, Misamis Occidental',
            'Bontoc, Mountain Province',
            'Bontoc, Southern Leyte',
            'Borbon, Cebu',
            'Boronga (Capital), Eastern Samar',
            'Boston, Davao Oriental',
            'Botolan, Zambales',
            'Braulio E. Dujali, Davao Del Norte',
            'Brooke Point, Palawan',
            'Bubong, Lanao Del Sur',
            'Bucay, Abra',
            'Bucloc, Abra',
            'Buenavista, Agusan Del Norte',
            'Buenavista, Bohol',
            'Buenavista, Guimaras',
            'Buenavista, Marinduque',
            'Buenavista, Quezon',
            'Bugallon, Pangasinan',
            'Bugasong, Antique',
            'Buguey, Cagayan',
            'Buguias, Benguet',
            'Buhi, Camarines Sur',
            'Bula, Camarines Sur',
            'Bulacan, Bulacan',
            'Bulalacao (San Pedro), Oriental Mindoro',
            'Bulan, Sorsogon',
            'Buldon, Maguindanao',
            'Buluan, Maguindanao',
            'Bulusan, Sorsogon',
            'Bunawan, Agusan Del Sur',
            'Burauen, Leyte',
            'Burdeos, Quezon',
            'Burgos, Ilocos Norte',
            'Burgos, Ilocos Sur',
            'Burgos, Isabela',
            'Burgos, La Union',
            'Burgos, Pangasinan',
            'Burgos, Surigao Del Norte',
            'Burungan, Aklan',
            'Bustos, Bulacan',
            'Busuanga, Palawan',
            'Butuan City (Capital), Agusan Del Norte',
            'Buug, Zamboanga Sibugay',
            'Caba, La Union',
            'Cabadbaran, Agusan Del Norte',
            'Cabagan, Isabela',
            'Cabanatuan City, Nueva Ecija',
            'Cabangan, Zambales',
            'Cabanglasan, Bukidnon',
            'Cabarroguis (Capital), Quirino',
            'Cabatuan, Iloilo',
            'Cabatuan, Isabela',
            'Cabiao, Nueva Ecija',
            'Cabucgayan, Biliran',
            'Cabugao, Ilocos Sur',
            'Cabuyao, Laguna',
            'Cadiz City, Negros Occidental',
            'Cagayan De Oro City (Capital), Misamis Oriental',
            'Cagayancillo, Palawan',
            'Cagdianao, Surigao Del Norte',
            'Cagwait, Surigao Del Sur',
            'Caibiran, Biliran',
            'Cainta, Rizal',
            'Cajidiocan, Romblon',
            'Calaca, Batangas',
            'Calamba City, Laguna',
            'Calamba, Misamis Occidental',
            'Calanasan (Bayag), Apayao',
            'Calanogas, Lanao Del Sur',
            'Calapan City, Oriental Mindoro',
            'Calape, Bohol',
            'Calasiao, Pangasinan',
            'Calatagan, Batangas',
            'Calatrava, Negros Occidental',
            'Calatrava, Romblon',
            'Calauag, Quezon',
            'Calauan, Laguna',
            'Calayan, Cagayan',
            'Calbayog City, Western Samar',
            'Calbiga, Western Samar',
            'Calinog, Iloilo',
            'Calintaan, Occidental Mindoro',
            'Caloocan City (North), Metro Manila',
            'Caloocan City (South), Metro Manila',
            'Calubian, Leyte',
            'Calumpit, Bulacan',
            'Caluya, Antique',
            'Camalaniugan, Cagayan',
            'Camalig, Albay',
            'Camaligan, Camarines Sur',
            'Camiling, Tarlac',
            'Can-Avid, Eastern Samar',
            'Canaman, Camarines Sur',
            'Candaba, Pampanga',
            'Candelaria, Quezon',
            'Candelaria, Zambales',
            'Candijay, Bohol',
            'Candon City, Ilocos Sur',
            'Candoni, Negros Occidental',
            'Cantilan, Surigao Del Sur',
            'Caoayan, Ilocos Sur',
            'Capalonga, Camarines Norte',
            'Capas, Tarlac',
            'Capoocan, Leyte',
            'Capul, Northern Samar',
            'Caraga, Davao Oriental',
            'Caramoran, Catanduanes',
            'Caranglan, Nueva Ecija',
            'Carasi, Ilocos Norte',
            'Carcar, Cebu',
            'Cardona, Rizal',
            'Carigara, Leyte',
            'Carles, Iloilo',
            'Carmen, Agusan Del Norte',
            'Carmen, Bohol',
            'Carmen, Cebu',
            'Carmen, Davao Del Norte',
            'Carmen, North Cotabato',
            'Carmen, Surigao Del Sur',
            'Carmona, Cavite',
            'Carrascal, Surigao Del Sur',
            'Casiguran, Sorsogon',
            'Castilla, Sorsogon',
            'Castillejos, Zambales',
            'Cataingan, Masbate',
            'Catanauan, Quezon',
            'Catarman, Camiguin',
            'Catarman, Northern Samar',
            'Catbalogan, Western Samar',
            'Cateel, Davao Oriental',
            'Catigbian, Bohol',
            'Catmon, Cebu',
            'Catubig, Northern Samar',
            'Cauayan City, Isabela',
            'Cauayan, Negros Occidental',
            'Cavinti, Laguna',
            'Cavite City, Cavite',
            'Cawayan, Masbate',
            'Cebu City, Cebu',
            'Cervantes, Ilocos Sur',
            'Clarin, Bohol',
            'Clarin, Misamis Occidental',
            'Claver, Surigao Del Norte',
            'Claveria, Cagayan',
            'Claveria, Masbate',
            'Claveria, Misamis Oriental',
            'Columbio, Sultan Kudarat',
            'Compostela, Cebu',
            'Compostela, Compostella Valley',
            'Concepcion, Iloilo',
            'Concepcion, Misamis Occidental',
            'Concepcion, Romblon',
            'Concepcion, Tarlac',
            'Conner, Apayao',
            'Consolacion, Cebu',
            'Corcuera, Romblon',
            'Cordon, Isabela',
            'Cordova, Cebu',
            'Corella, Bohol',
            'Coron, Palawan',
            'Cortes, Bohol',
            'Cortes, Surigao Del Sur',
            'Cuartero, Capiz',
            'Cuenca, Batangas',
            'Culaba, Biliran',
            'Culasi, Antique',
            'Culion, Palawan',
            'Currimao, Ilocos Norte',
            'Cuyapo, Nueva Ecija',
            'Cuyo, Palawan',
            'Daanbantayan, Cebu',
            'Daet, Camarines Norte',
            'Dagami, Leyte',
            'Dagohoy, Bohol',
            'Daguioman, Abra',
            'Dagupan City, Pangasinan',
            'Dalaguete, Cebu',
            'Damulog, Bukidnon',
            'Danao City, Cebu',
            'Danao, Bohol',
            'Dangcagan, Bukidnon',
            'Danglas, Abra',
            'Dao, Capiz',
            'Dapa, Surigao Del Norte',
            'Dapitan City, Zamboanga Del Norte',
            'Daraga, Albay',
            'Daram, Western Samar',
            'Dasmarinas, Cavite',
            'Dasol, Pangasinan',
            ' Datu Abdullah Sanki, Maguindanao',
            'Datu Odin Sinsuat, Maguindanao',
            'Datu Paglas, Maguindanao',
            'Datu Piang, Maguindanao',
            'Datu Saudi Ampatuan, Maguindanao',
            'Datu Unsay, Maguindanao',
            'Dauin, Negros Oriental',
            'Dauis, Bohol',
            'Davao City, Davao Del Sur',
            'Del Carmen, Surigao Del Norte',
            'Del Gallego, Camarines Sur',
            'Delfin Albano (Magsaysay), Isabela',
            'Diadi, Nueva Vizcaya',
            'Diffun, Quirino',
            'Digos City (Capital), Davao Del Sur',
            'Dimasalang, Masbate',
            'Dimataling, Zamboanga Del Sur',
            'Dimiao, Bohol',
            'Dinagat, Surigao Del Norte',
            'Dinalupihan, Bataan',
            'Dinapigue, Isabela',
            'Dinas, Zamboanga Del Sur',
            'Dingle, Iloilo',
            'Dingras, Ilocos Norte',
            'Diplahan, Zamboanga Sibugay',
            'Dipolog City (Capital), Zamboanga Del Norte',
            'Divilican, Isabela',
            'Dolores, Abra',
            'Dolores, Eastern Samar',
            'Dolores, Quezon',
            'Don Carlos, Bukidnon',
            'Don Marcelino, Davao Del Sur',
            'Don Victoriano Chiongbian (Don, Misamis Occidental',
            'Dona Remedios Trinidad, Bulacan',
            'Donsol, Sorsogon',
            'Duenas, Iloilo',
            'Duero, Bohol',
            'Dulag, Leyte',
            ' Dumaguete, Negros Oriental',
            'Dumalag, Capiz',
            'Dumalneg, Ilocos Norte',
            'Dumangas, Iloilo',
            'Dumanjug, Cebu',
            'Dumaran, Palawan',
            'Dumarao, Capiz',
            'Dumingag, Zamboanga Del Sur',
            'Dupax Del Norte, Nueva Vizcaya',
            'Dupax Del Sur, Nueva Vizcaya',
            'Echague, Isabela',
            'El Nido (Bacuit), Palawan',
            'El Salvador, Misamis Oriental',
            'Enrile, Cagayan',
            'Enrique B. Magalona (Saravia), Negros Occidental',
            'Enrique Villanueva, Siquijor',
            'Escalante City, Negros Occidental',
            'Esperanza, Agusan Del Sur',
            'Esperanza, Masbate',
            'Esperanza, Sultan Kudarat',
            'Estancia, Iloilo',
            'Famy, Laguna',
            'Ferrol, Romblon',
            'Flora, Apayao',
            'Floridablanca, Pampanga',
            'Gabaldon (Bitulok & Sarabani), Nueva Ecija',
            'Gainza, Camarines Sur',
            'Galimuyod, Ilocos Sur',
            'Gamay, Northern Samar',
            'Gamu, Isabela',
            'Gandara, Western Samar',
            'Gapan City, Nueva Ecija',
            'Garcia Hernandez, Bohol',
            'Gasan, Marinduque',
            'Gattaran, Cagayan',
            'Gen. Mariano Alvarez, Cavite',
            'Gen. S. K. Pendatun, Maguindanao',
            'General Emilio Aguinaldo, Cavite',
            'General Luna, Quezon',
            'General Luna, Surigao Del Norte',
            'General Macarthur, Eastern Samar',
            'General Mamerto Natividad, Nueva Ecija',
            'General Nakar, Quezon',
            'General Santos City (Dadiangas, South Cotabato',
            'General Tinio (Payapa), Nueva Ecija',
            'General Trias, Cavite',
            'Gerona, Tarlac',
            'Gigaquit, Surigao Del Norte',
            'Gigmoto, Catanduanes',
            'Ginatilan, Cebu',
            'Gingoog City, Misamis Oriental',
            'Giporlos, Eastern Samar',
            'Gitagum, Misamis Oriental',
            'Glan, Sarangani',
            'Gloria, Oriental Mindoro',
            'Goa, Camarines Sur',
            'Godod, Zamboanga Del Norte',
            'Gonzaga, Cagayan',
            'Gregorio Del Pilar (Concepcion, Ilocos Sur',
            'Guagua, Pampanga',
            'Gubat, Sorsogon',
            'Guiguinto, Bulacan',
            'Guihulngan, Negros Oriental',
            'Guimba, Nueva Ecija',
            'Guimbal, Iloilo',
            'Guinayangan, Quezon',
            'Guindulman, Bohol',
            'Guindulungan, Maguindanao',
            'Guinobatan, Albay',
            'Guinsiliban, Camiguin',
            'Guipos, Zamboanga Del Sur',
            'Guiuan, Eastern Samar',
            'Gumaca, Quezon',
            'Gutalac, Zamboanga Del Norte',
            'Hadji Panglima Tahil (Marungga, Sulu',
            'Hagonoy, Bulacan',
            'Hagonoy, Davao Del Sur',
            'Hamtic, Antique',
            'Hermosa, Bataan',
            'Hernani, Eastern Samar',
            'Hilongos, Leyte',
            'Himamaylan City, Negros Occidental',
            'Hinabangan, Western Samar',
            'Hinatuan, Surigao Del Sur',
            'Hindang, Leyte',
            'Hingyon, Ifugao',
            'Hinigaran, Negros Occidental',
            'Hinoba-An (Asia), Negros Occidental',
            'Hinunangan, Southern Leyte',
            'Hinundayan, Southern Leyte',
            'Hungduan, Ifugao',
            'Iba (Capital), Zambales',
            'Ibaan, Batangas',
            'Ibajay, Aklan',
            'Igbaras, Iloilo',
            'Iguig, Cagayan',
            'Ilagan, Isabela',
            'Iligan City (44 Bgys), Lanao Del Norte',
            'Ilog, Negros Occidental',
            'Iloilo City, Iloilo',
            'Imelda, Zamboanga Sibugay',
            'Impasug-Ong, Bukidnon',
            'Imus, Cavite',
            'Inabangay, Bohol',
            'Indanan, Sulu',
            'Indang, Cavite',
            'Infanta, Pangasinan',
            'Infanta, Quezon',
            'Initao, Misamis Oriental',
            'Inopacan, Leyte',
            'Ipil, Zamboanga Sibugay',
            'Iriga City, Camarines Sur',
            'Irosin, Sorsogon',
            'Isabel, Leyte',
            'Isabela, Negros Occidental',
            'Isulan, Sultan Kudarat',
            'Itbayat, Batanes',
            ' Itogon, Benguet',
            'Ivana, Batanes',
            'Ivisan, Capiz',
            'Jabonga, Agusan Del Norte',
            'Jaen, Nueva Ecija',
            'Jagna, Bohol',
            'Jala-Jala, Rizal',
            'Jamindan, Capiz',
            'Janiuay, Iloilo',
            'Jaro, Leyte',
            'Jasaan, Misamis Oriental',
            'Javier (Bugho), Leyte',
            'Jetafe, Bohol',
            'Jiabong, Western Samar',
            'Jimalalud, Negros Oriental',
            'Jimenez, Misamis Occidental',
            'Jipapad, Eastern Samar',
            'Jolo (Capital), Sulu',
            'Jomalig, Quezon',
            'Jones, Isabela',
            'Jordan, Guimaras',
            'Jose Abad Santos (Trinidad), Davao Del Sur',
            'Jose Dalman (Ponot), Zamboanga Del Norte',
            'Jose Panganiban, Camarines Norte',
            'Josefina, Zamboanga Del Sur',
            'Jovellar, Albay',
            'Juban, Sorsogon',
            'Julita, Leyte',
            'Kabacan, North Cotabato',
            'Kabankalan City, Negros Occidental',
            'Kabasalan, Zamboanga Sibugay',
            'Kabayan, Benguet',
            'Kabugao, Apayao',
            'Kabuntalan, Maguindanao',
            'Kadingilan, Bukidnon',
            'Kalamansig, Sultan Kudarat',
            'Kalawit, Zamboanga Del Norte',
            'Kalayaan, Laguna',
            'Kalayaan, Palawan',
            'Kalibo, Aklan',
            'Kalilangan, Bukidnon',
            'Kalingalan Caluang, Sulu',
            'Kananga, Leyte',
            'Kapalong, Davao Del Norte',
            'Kapangan, Benguet',
            'Kapatagan, Lanao Del Norte',
            'Katipunan, Zamboanga Del Norte',
            'Kauswagan, Lanao Del Norte',
            'Kawayan, Biliran',
            'Kawit, Cavite',
            'Kayapa, Nueva Vizcaya',
            'Kiamba, Sarangani',
            'Kiangan, Ifugao',
            'Kibawe, Bukidnon',
            'Kiblawan, Davao Del Sur',
            'Kibungan, Benguet',
            'Kidapawan City (Capital), North Cotabato',
            'Kinoguitan, Misamis Oriental',
            'Kitaotao, Bukidnon',
            'Kitcharao, Agusan Del Norte',
            'Kolambugan, Lanao Del Norte',
            'Koronadal City (Capital), South Cotabato',
            'Kumalarang, Zamboanga Del Sur',
            'La Carlota City, Negros Occidental',
            'La Castellana, Negros Occidental',
            'La Libertad, Negros Oriental',
            'La Libertad, Zamboanga Del Norte',
            'La Paz, Abra',
            'La Paz, Agusan Del Sur',
            'La Paz, Leyte',
            'La Trinidad, Benguet',
            'Laak (San Vicente), Compostella Valley',
            'Labangan, Zamboanga Del Sur',
            'Labason, Zamboanga Del Norte',
            'Labo, Camarines Norte',
            'Labrador, Pangasinan',
            'Lacub, Abra',
            'Lagangilang, Abra',
            'Lagawe, Ifugao',
            'Lagayan, Abra',
            'Lagonglong, Misamis Oriental',
            'Lagonoy, Camarines Sur',
            'Laguindingan, Misamis Oriental',
            'Lake Sebu, South Cotabato',
            'Lakewood, Zamboanga Del Sur',
            'Lal-Lo, Cagayan',
            'Lala, Lanao Del Norte',
            'Lambayong (Mariano Marcos), Sultan Kudarat',
            'Lambunao, Iloilo',
            'Lamitan, Basilan',
            'Lamut, Ifugao',
            'Langiden, Abra',
            'Languyan, Tawi-tawi',
            'Lantapan, Bukidnon',
            'Lantawan, Basilan',
            'Lanuza, Surigao Del Sur',
            'Laoac, Pangasinan',
            'Laoag City (Capital), Ilocos Norte',
            'Laoang, Northern Samar',
            'Lapaz, Tarlac',
            'Lapinig, Northern Samar',
            'Lapu-Lapu City, Cebu',
            'Lapuyan, Zamboanga Del Sur',
            'Larena, Siquijor',
            'Las Navas, Northern Samar',
            'Las Nieves, Agusan Del Norte',
            'Las Pinas City, Metro Manila',
            'Lasam, Cagayan',
            'Laua-An, Antique',
            'Laur, Nueva Ecija',
            'Laurel, Batangas',
            'Lavezares, Northern Samar',
            'Lawaan, Eastern Samar',
            'Lazi, Siquijor',
            'Lebak, Sultan Kudarat',
            'Leganes, Iloilo',
            'Legazpi City, Albay',
            'Lemery, Batangas',
            'Lemery, Iloilo',
            'Leon, Iloilo',
            'Leyte, Leyte',
            'Lezo, Aklan',
            'Lian, Batangas',
            'Lianga, Surigao Del Sur',
            'Libacao, Aklan',
            'Libagon, Southern Leyte',
            'Libertad, Antique',
            'Libertad, Misamis Oriental',
            'Libjo (Albor), Surigao Del Norte',
            'Libmanan, Camarines Sur',
            'Libon, Albay',
            'Libona, Bukidnon',
            'Libungan, North Cotabato',
            'Licab, Nueva Ecija',
            'Lidlidda, Ilocos Sur',
            'Ligao City, Albay',
            'Lila, Bohol',
            'Liliw, Laguna',
            'Liloan, Cebu',
            'Liloan, Southern Leyte',
            'Liloy, Zamboanga Del Norte',
            'Limasawa, Southern Leyte',
            'Limay, Bataan',
            'Linamon, Lanao Del Norte',
            'Linapacan, Palawan',
            'Lingayen, Pangasinan',
            'Lingig, Surigao Del Sur',
            'Lipa City, Batangas',
            'Llanera, Nueva Ecija',
            'Llorente, Eastern Samar',
            'Loay, Bohol',
            'Lobo, Batangas',
            'Loboc, Bohol',
            'Looc, Occidental Mindoro',
            'Looc, Romblon',
            'Loon, Bohol',
            'Lope De Vega, Northern Samar',
            'Lopez Jaena, Misamis Occidental',
            'Lopez, Quezon',
            'Loreto, Agusan Del Sur',
            'Loreto, Surigao Del Norte',
            'Los Banos, Laguna',
            'Luba, Abra',
            'Lubang, Occidental Mindoro',
            'Lubao, Pampanga',
            'Lucban, Quezon',
            'Lucena City, Quezon',
            'Lugait, Misamis Oriental',
            'Lugus, Sulu',
            'Luisiana, Laguna',
            'Lumban, Laguna',
            'Lumbatan, Lanao Del Sur',
            'Lumbayanague, Lanao Del Sur',
            'Luna, Apayao',
            'Luna, Isabela',
            'Luna, La Union',
            'Lupao, Nueva Ecija',
            'Lupi, Camarines Sur',
            'Lupon, Davao Oriental',
            'Lutayan, Sultan Kudarat',
            'Luuk, Sulu',
            'Mlang, North Cotabato',
            'Ma-Ayon, Capiz',
            'Maasim, Sarangani',
            'Maasin City, Southern Leyte',
            'Maasin, Iloilo',
            'Mabalacat, Pampanga',
            'Mabinay, Negros Oriental',
            'Mabini (Dona Alicia), Compostella Valley',
            'Mabini, Batangas',
            'Mabini, Bohol',
            'Mabini, Pangasinan',
            'Mabitac, Laguna',
            'Mabuhay, Zamboanga Sibugay',
            'Macabebe, Pampanga',
            'Macalelon, Quezon',
            'Macarthur, Leyte',
            'Maco, Compostella Valley',
            'Maconacon, Isabela',
            'Macrohon, Southern Leyte',
            'Madalag, Aklan',
            'Madalum, Lanao Del Sur',
            ' Maddela, Quirino',
            'Madrid, Surigao Del Sur',
            'Madridejos, Cebu',
            'Magalang, Pampanga',
            'Magallanes, Agusan Del Norte',
            'Magallanes, Cavite',
            'Magallanes, Sorsogon',
            'Magarao, Camarines Sur',
            'Magdalena, Laguna',
            'Magdiwang, Romblon',
            'Magpet, North Cotabato',
            'Magsaysay (Linugos), Misamis Oriental',
            'Magsaysay, Davao Del Sur',
            'Magsaysay, Lanao Del Norte',
            'Magsaysay, Occidental Mindoro',
            'Magsaysay, Palawan',
            'Magsingal, Ilocos Sur',
            'Mahaplag, Leyte',
            'Mahatao, Batanes',
            'Mahayag, Zamboanga Del Sur',
            'Mahinog, Camiguin',
            'Maigo, Lanao Del Norte',
            'Maimbung, Sulu',
            'Mainit, Surigao Del Norte',
            'Maitum, Sarangani',
            'Majayjay, Laguna',
            'Makati City, Metro Manila',
            'Makato, Aklan',
            'Makilala, North Cotabato',
            'Malabon City, Metro Manila',
            'Malabuyoc, Cebu',
            'Malalag, Davao Del Sur',
            'Malangas, Zamboanga Sibugay',
            'Malapatan, Sarangani',
            'Malasiqui, Pangasinan',
            'Malay, Aklan',
            'Malaybalay City (Capital), Bukidnon',
            'Malibcong, Abra',
            'Malilipot, Albay',
            'Malimono, Surigao Del Norte',
            ' Malinao, Aklan',
            'Malinao, Albay',
            'Malita, Davao Del Sur',
            'Malitbog, Bukidnon',
            'Malitbog, Southern Leyte',
            'Mallig, Isabela',
            'Malolos, Bulacan',
            'Malungon, Sarangani',
            'Maluso, Basilan',
            'Malvar, Batangas',
            'Mamasapano, Maguindanao',
            'Mambajao, Camiguin',
            'Mamburao, Occidental Mindoro',
            'Mambusao, Capiz',
            'Manabo, Abra',
            'Manaoag, Pangasinan',
            'Manapla, Negros Occidental',
            'Manay, Davao Oriental',
            'Mandaluyong City, Metro Manila',
            'Mandaon, Masbate',
            'Mandaue City, Cebu',
            'Mangaldan, Pangasinan',
            'Mangatarem, Pangasinan',
            'Manila City, Metro Manila',
            'Manito, Albay',
            'Manjuyod, Negros Oriental',
            'Mankayan, Benguet',
            'Manolo Fortich, Bukidnon',
            'Mansalay, Oriental Mindoro',
            'Manticao, Misamis Oriental',
            'Manukan, Zamboanga Del Norte',
            'Mapanas, Northern Samar',
            'Mapandan, Pangasinan',
            'Mapun (Cagayan De Tawi-Tawi), Tawi-tawi',
            'Marabut, Western Samar',
            'Maragondon, Cavite',
            'Maragusan (San Mariano), Compostella Valley',
            'Maramag, Bukidnon',
            'Marantao, Lanao Del Sur',
            'Marcos, Ilocos Norte',
            'Margosatubig, Zamboanga Del Sur',
            'Maria, Siquijor',
            'Maribojoc, Bohol',
            'Marihatag, Surigao Del Sur',
            'Marikina City, Metro Manila',
            'Marilao, Bulacan',
            'Maripipi, Biliran',
            'Mariveles, Bataan',
            'Marogong, Lanao Del Sur',
            'Masantol, Pampanga',
            'Masbate City (Capital), Masbate',
            'Masinloc, Zambales',
            'Maslog, Eastern Samar',
            'Mataas Na Kahoy, Batangas',
            'Matag-Ob, Leyte',
            'Matalam, North Cotabato',
            'Matalom, Leyte',
            'Matanao, Davao Del Sur',
            'Matanog, Maguindanao',
            'Matnog, Sorsogon',
            'Matuguinao, Western Samar',
            'Matungao, Lanao Del Norte',
            'Mauban, Quezon',
            'Mawab, Compostella Valley',
            'Mayantoc, Tarlac',
            'Maydolong, Eastern Samar',
            'Mayorga, Leyte',
            'Mayoyao, Ifugao',
            'Medellin, Cebu',
            'Medina, Misamis Oriental',
            'Mendez (Mendez-Nunez), Cavite',
            'Mercedes, Camarines Norte',
            'Mercedes, Eastern Samar',
            'Merida, Leyte',
            'Mexico, Pampanga',
            'Meycauayan, Bulacan',
            'Miagao, Iloilo',
            'Midsalip, Zamboanga Del Sur',
            'Midsayap, North Cotabato',
            'Milagros, Masbate',
            'Milaor, Camarines Sur',
            'Mina, Iloilo',
            'Minalabac, Camarines Sur',
            'Minalin, Pampanga',
            'Minglanilla, Cebu',
            'Moalboal, Cebu',
            'Mobo, Masbate',
            'Mogpog, Marinduque',
            'Moises Padilla (Magallon), Negros Occidental',
            'Molave, Zamboanga Del Sur',
            'Mondragon, Northern Samar',
            'Monkayo, Compostella Valley',
            'Monreal, Masbate',
            'Montevista, Compostella Valley',
            'Morong, Bataan',
            'Morong, Rizal',
            'Motiong, Western Samar',
            'Mulanay, Quezon',
            'Munai, Lanao Del Norte',
            'Muntinlupa City, Metro Manila',
            'Murcia, Negros Occidental',
            'Mutia, Zamboanga Del Norte',
            'Muñoz City, Nueva Ecija',
            'Naawan, Misamis Oriental',
            'Nabas, Aklan',
            'Nabua, Camarines Sur',
            'Nabunturan, Compostella Valley',
            'Naga City, Camarines Sur',
            'Naga, Cebu',
            'Naga, Zamboanga Sibugay',
            'Nagbukel, Ilocos Sur',
            'Nagcarlan, Laguna',
            'Nagtipunan, Quirino',
            'Naguilan, Isabela',
            'Naguilian, La Union',
            'Naic, Cavite',
            'Nampicuan, Nueva Ecija',
            'Narra, Palawan',
            'Narvacan, Ilocos Sur',
            'Nasipit, Agusan Del Norte',
            'Nasugbu, Batangas',
            'Natividad, Pangasinan',
            'Natonin, Mountain Province',
            'Naujan, Oriental Mindoro',
            'Naval, Biliran',
            'Navotas, Metro Manila',
            'New Bataan, Compostella Valley',
            'New Corella, Davao Del Norte',
            'New Lucena, Iloilo',
            'New Washington, Aklan',
            'Norala, South Cotabato',
            'Norzagaray, Bulacan',
            'Noveleta, Cavite',
            'Nueva Era, Ilocos Norte',
            'Nueva Valencia, Guimaras',
            'Numancia, Aklan',
            'Nunungan, Lanao Del Norte',
            'Oas, Albay',
            'Obando, Bulacan',
            'Ocampo, Camarines Sur',
            'Odiongan, Romblon',
            'Old Panamao, Sulu',
            'Olonggapo City, Zambales',
            'Olutanga, Zamboanga Sibugay',
            'Opol, Misamis Oriental',
            'Orani, Bataan',
            'Oras, Eastern Samar',
            'Orion, Bataan',
            'Ormoc City, Leyte',
            'Oroquieta City (Capital), Misamis Occidental',
            'Oslob, Cebu',
            'Oton, Iloilo',
            'Ozamis City, Misamis Occidental',
            'Padada, Davao Del Sur',
            'Padre Burgos, Quezon',
            'Padre Burgos, Southern Leyte',
            'Padre Garcia, Batangas',
            'Paete, Laguna',
            'Pagadian City (Capital), Zamboanga Del Sur',
            'Pagagawan, Maguindanao',
            'Pagalungan, Maguindanao',
            'Pagayawan (Tatarikan), Lanao Del Sur',
            'Pagbilao, Quezon',
            'Paglat, Maguindanao',
            'Pagsanghan, Western Samar',
            'Pagsanjan, Laguna',
            'Pagudpud, Ilocos Norte',
            'Pakil, Laguna',
            'Palanan, Isabela',
            'Palanas, Masbate',
            'Palapag, Northern Samar',
            'Palauig, Zambales',
            'Palayan City, Nueva Ecija',
            'Palimbang, Sultan Kudarat',
            'Palo, Leyte',
            'Palompon, Leyte',
            'Paluan, Occidental Mindoro',
            'Pambujan, Northern Samar',
            'Pamplona, Cagayan',
            'Pamplona, Camarines Sur',
            'Pamplona, Negros Oriental',
            'Panabo City, Davao Del Norte',
            'Panaon, Misamis Occidental',
            'Panay, Capiz',
            'Pandami, Sulu',
            'Pandan, Antique',
            'Pandan, Catanduanes',
            'Pandi, Bulacan',
            'Panganiban, Catanduanes',
            'Pangantucan, Bukidnon',
            'Pangil, Laguna',
            'Panglao, Bohol',
            'Panglima Estino (New Panamao), Sulu',
            'Panglima Sugala (Balimbing), Tawi-tawi',
            'Pangutaran, Sulu',
            'Paniqui, Tarlac',
            'Panitan, Capiz',
            'Pantabangan, Nueva Ecija',
            'Pantao Ragat, Lanao Del Norte',
            'Pantar, Lanao Del Norte',
            'Pantukan, Compostella Valley',
            'Panukulan, Quezon',
            'Paoay, Ilocos Norte',
            'Paombong, Bulacan',
            'Paracale, Camarines Norte',
            'Paracelis, Mountain Province',
            'Paranaque City, Metro Manila',
            'Paranas (Wright), Western Samar',
            'Parang, Maguindanao',
            'Parang, Sulu',
            'Pasacao, Camarines Sur',
            'Pasay City, Metro Manila',
            'Pasig City, Metro Manila',
            'Pasil, Kalinga',
            'Passi City, Iloilo',
            'Pastrana, Leyte',
            'Pasuquin, Ilocos Norte',
            'Pata, Sulu',
            'Pateros, Metro Manila',
            'Patikul, Sulu',
            'Patnanungan, Quezon',
            'Patnongon, Antique',
            'Pavia, Iloilo',
            'Payao, Zamboanga Sibugay',
            'Penablanca, Cagayan',
            'Penaranda, Nueva Ecija',
            'Penarubia, Abra',
            'Perez, Quezon',
            'Piagapo, Lanao Del Sur',
            'Piat, Cagayan',
            'Piddig, Ilocos Norte',
            'Pidigan, Abra',
            'Pigkawayan, North Cotabato',
            'Pikit, North Cotabato',
            'Pila, Laguna',
            'Pilar, Abra',
            'Pilar, Bataan',
            'Pilar, Bohol',
            'Pilar, Capiz',
            'Pilar, Cebu',
            'Pilar, Sorsogon',
            'Pilar, Surigao Del Norte',
            'Pili, Camarines Sur',
            'Pililla, Rizal',
            'Pinabacdao, Western Samar',
            'Pinamalayan, Oriental Mindoro',
            'Pinamungahan, Cebu',
            'Pinan (New Pinan), Zamboanga Del Norte',
            'Pinili, Ilocos Norte',
            'Pintuyan, Southern Leyte',
            'Pinukpuk, Kalinga',
            'Pio Duran, Albay',
            'Pio V. Corpuz (Limbuhan), Masbate',
            'Pitogo, Quezon',
            'Pitogo, Zamboanga Del Sur',
            'Placer, Masbate',
            'Placer, Surigao Del Norte',
            'Plaridel, Bulacan',
            'Plaridel, Misamis Occidental',
            'Plaridel, Quezon',
            'Pola, Oriental Mindoro',
            'Polanco, Zamboanga Del Norte',
            'Polangui, Albay',
            'Polillo, Quezon',
            'Polomolok, South Cotabato',
            'Pontevedra, Capiz',
            'Pontevedra, Negros Occidental',
            'Poona Bayabao (Gata), Lanao Del Sur',
            'Poona Piagapo, Lanao Del Norte',
            'Popo, Cebu',
            'Porac, Pampanga',
            'Pototan, Iloilo',
            'Pozorrubio, Pangasinan',
            'Pres. Carlos P. Garcia (Pitogo, Bohol',
            'Pres. Manuel A. Roxas, Zamboanga Del Norte',
            'Presentacion (Parubcan), Camarines Sur',
            'President Quirino, Sultan Kudarat',
            'President Roxas, Capiz',
            'President Roxas, North Cotabato',
            ' Prieto Diaz, Sorsogon',
            'Prosperidad (Capital), Agusan Del Sur',
            'Pudtol, Apayao',
            'Puerto Galera, Oriental Mindoro',
            'Puerto Princesa City, Palawan',
            'Pulilan, Bulacan',
            'Pulupandan, Negros Occidental',
            'Pura, Tarlac',
            'Quezon City, Metro Manila',
            'Quezon, Bukidnon',
            'Quezon, Isabela',
            'Quezon, Nueva Ecija',
            'Quezon, Nueva Vizcaya',
            'Quezon, Palawan',
            'Quezon, Quezon',
            'Quinapondan, Eastern Samar',
            'Quirino (Angkaki), Ilocos Sur',
            'Quirino, Isabela',
            'Ragay, Camarines Sur',
            'Ramon Magsaysay (Liargo), Zamboanga Del Sur',
            'Ramon, Isabela',
            'Ramos, Tarlac',
            'Rapu-Rapu, Albay',
            'Real, Quezon',
            'Reina Mercedes, Isabela',
            'Remedios T. Romualdez, Agusan Del Norte',
            'Rizal (Liwan), Kalinga',
            'Rizal (Marcos), Palawan',
            'Rizal, Cagayan',
            'Rizal, Laguna',
            'Rizal, Nueva Ecija',
            'Rizal, Occidental Mindoro',
            'Rizal, Zamboanga Del Norte',
            'Rodriguez (Montalban), Rizal',
            'Romblon, Romblon',
            'Ronda, Cebu',
            'Rosales, Pangasinan',
            'Rosario, Agusan Del Sur',
            'Rosario, Cavite',
            'Rosario, La Union',
            ' Rosario, Northern Samar',
            'Roseller Lim, Zamboanga Sibugay',
            'Roxas City (Capital), Capiz',
            'Roxas, Isabela',
            'Roxas, Oriental Mindoro',
            'Roxas, Palawan',
            'Sabangan, Mountain Province',
            'Sablan, Benguet',
            'Sablan, Occidental Mindoro',
            'Sabtang, Batanes',
            'Sadanga, Mountain Province',
            'Sagada, Mountain Province',
            'Sagay City, Negros Occidental',
            'Sagay, Camiguin',
            'Sagbayan (Borja), Bohol',
            'Sagnay, Camarines Sur',
            'Saguday, Quirino',
            'Saint Bernard, Southern Leyte',
            'Salay, Misamis Oriental',
            'Salcedo (Baugen), Ilocos Sur',
            'Salcedo, Eastern Samar',
            'Sallapadan, Abra',
            'Salug, Zamboanga Del Norte',
            'Salvador Benedicto, Negros Occidental',
            'Salvador, Lanao Del Norte',
            'Samal Island Garden City, Davao Del Norte',
            'Samal, Bataan',
            'Samboan, Cebu',
            'Sampaloc, Quezon',
            'San Agustin, Isabela',
            'San Agustin, Romblon',
            'San Agustin, Surigao Del Sur',
            'San Andres (Calolbon), Catanduanes',
            'San Andres, Quezon',
            'San Andres, Romblon',
            'San Antonio, Northern Samar',
            'San Antonio, Nueva Ecija',
            'San Antonio, Quezon',
            'San Antonio, Zambales',
            'San Benito, Surigao Del Norte',
            'San Carlos City, Negros Occidental',
            'San Carlos City, Pangasinan',
            'San Clemente, Tarlac',
            'San Dionisio, Iloilo',
            'San Emilio, Ilocos Sur',
            'San Enrique, Iloilo',
            'San Enrique, Negros Occidental',
            'San Esteban, Ilocos Sur',
            'San Fabian, Pangasinan',
            'San Felipe, Zambales',
            'San Fernando City (Capital), La Union',
            'San Fernando City, Pampanga',
            'San Fernando, Bukidnon',
            'San Fernando, Camarines Sur',
            'San Fernando, Cebu',
            'San Fernando, Masbate',
            'San Fernando, Romblon',
            'San Francisco (Anao-Aon), Surigao Del Norte',
            'San Francisco (Aurora), Quezon',
            'San Francisco, Agusan Del Sur',
            'San Francisco, Cebu',
            'San Francisco, Southern Leyte',
            'San Gabriel, La Union',
            'San Guillermo, Isabela',
            'San Ildefonso, Bulacan',
            'San Ildefonso, Ilocos Sur',
            'San Isidro, Abra',
            'San Isidro, Bohol',
            'San Isidro, Davao Oriental',
            'San Isidro, Isabela',
            'San Isidro, Leyte',
            'San Isidro, Northern Samar',
            'San Isidro, Nueva Ecija',
            'San Isidro, Surigao Del Norte',
            'San Jacinto, Masbate',
            'San Jacinto, Pangasinan',
            'San Joaquin, Iloilo',
            'San Jorge, Western Samar',
            'San Jose City, Nueva Ecija',
            'San Jose De Buan, Western Samar',
            'San Jose Del Monte City, Bulacan',
            'San Jose, Antique',
            'San Jose, Batangas',
            'San Jose, Camarines Sur',
            'San Jose, Negros Oriental',
            'San Jose, Northern Samar',
            'San Jose, Occidental Mindoro',
            'San Jose, Romblon',
            'San Jose, Surigao Del Norte',
            'San Jose, Tarlac',
            'San Juan (Cabalian), Southern Leyte',
            'San Juan (Lapog), Ilocos Sur',
            'San Juan, Abra',
            'San Juan, Batangas',
            'San Juan, La Union',
            'San Juan, Metro Manila',
            'San Juan, Siquijor',
            'San Julian, Eastern Samar',
            'San Leonardo, Nueva Ecija',
            'San Lorenzo Ruiz (Imelda), Camarines Norte',
            'San Lorenzo, Guimaras',
            'San Luis, Agusan Del Sur',
            'San Luis, Batangas',
            'San Luis, Pampanga',
            'San Manuel, Isabela',
            'San Manuel, Pangasinan',
            'San Manuel, Tarlac',
            'San Marcelino, Zambales',
            'San Mariano, Isabela',
            'San Mateo, Isabela',
            'San Mateo, Rizal',
            'San Miguel, Bohol',
            'San Miguel, Bulacan',
            'San Miguel, Catanduanes',
            'San Miguel, Iloilo',
            'San Miguel, Leyte',
            'San Miguel, Surigao Del Sur',
            'San Miguel, Zamboanga Del Sur',
            'San Narciso, Quezon',
            'San Narciso, Zambales',
            'San Nicolas, Batangas',
            'San Nicolas, Ilocos Norte',
            'San Nicolas, Pangasinan',
            'San Pablo City, Laguna',
            'San Pablo, Isabela',
            'San Pablo, Zamboanga Del Sur',
            'San Pascual, Batangas',
            'San Pascual, Masbate',
            'San Pedro, Laguna',
            'San Policarpo, Eastern Samar',
            'San Quintin, Abra',
            'San Quintin, Pangasinan',
            'San Rafael, Bulacan',
            'San Rafael, Iloilo',
            'San Remigio, Antique',
            'San Remigio, Cebu',
            'San Ricardo, Southern Leyte',
            'San Roque, Northern Samar',
            'San Sebastian, Western Samar',
            'San Simon, Pampanga',
            'San Teodoro, Oriental Mindoro',
            'San Vicente, Camarines Norte',
            'San Vicente, Ilocos Sur',
            'San Vicente, Northern Samar',
            'San Vicente, Palawan',
            'Sanchez-Mira, Cagayan',
            'Santa Ana, Cagayan',
            'Santa Ana, Pampanga',
            'Santa Barbara, Iloilo',
            'Santa Barbara, Pangasinan',
            'Santa Catalina, Ilocos Sur',
            'Santa Catalina, Negros Oriental',
            'Santa Cruz, Davao Del Sur',
            'Santa Cruz, Ilocos Sur',
            'Santa Cruz, Laguna',
            'Santa Cruz, Marinduque',
            'Santa Cruz, Occidental Mindoro',
            ' Santa Cruz, Zambales',
            'Santa Elena, Camarines Norte',
            'Santa Fe, Cebu',
            'Santa Fe, Leyte',
            'Santa Fe, Nueva Vizcaya',
            'Santa Fe, Romblon',
            'Santa Ignacia, Tarlac',
            'Santa Josefa, Agusan Del Sur',
            'Santa Lucia, Ilocos Sur',
            'Santa Magdalena, Sorsogon',
            'Santa Marcela, Apayao',
            'Santa Margarita, Western Samar',
            'Santa Maria (Imelda), Romblon',
            'Santa Maria, Bulacan',
            'Santa Maria, Davao Del Sur',
            'Santa Maria, Ilocos Sur',
            'Santa Maria, Isabela',
            'Santa Maria, Laguna',
            'Santa Maria, Pangasinan',
            'Santa Monica, Surigao Del Norte',
            'Santa Praxedes, Cagayan',
            'Santa Rita, Pampanga',
            'Santa Rita, Western Samar',
            'Santa Rosa, Laguna',
            'Santa Rosa, Nueva Ecija',
            'Santa Teresita, Batangas',
            'Santa Teresita, Cagayan',
            'Santa, Ilocos Sur',
            'Santander, Cebu',
            'Santiago City, Isabela',
            'Santiago, Agusan Del Norte',
            'Santiago, Ilocos Sur',
            'Santo Domingo (Libog), Albay',
            'Santo Domingo, Ilocos Sur',
            'Santo Domingo, Nueva Ecija',
            'Santo Nino (Faire), Cagayan',
            'Santo Nino, South Cotabato',
            'Santo Nino, Western Samar',
            'Santo Tomas, Batangas',
            'Santo Tomas, Davao Del Norte',
            'Santo Tomas, Isabela',
            'Santo Tomas, La Union',
            'Santo Tomas, Pampanga',
            'Santo Tomas, Pangasinan',
            'Santol, La Union',
            'Sapa-Sapa, Tawi-tawi',
            'Sapad, Lanao Del Norte',
            'Sapang Dalaga, Misamis Occidental',
            'Sapi-An, Capiz',
            'Sara, Iloilo',
            'Sarangani, Davao Del Sur',
            'Sariaya, Quezon',
            'Sarrat, Ilocos Norte',
            'Sasmoan (Sexmoan), Pampanga',
            'Sebaste, Antique',
            'Sen. Ninoy Aquino, Sultan Kudarat',
            'Sergio Osmena Sr., Zamboanga Del Norte',
            'Sevilla, Bohol',
            'Shariff Aguak, Maguindanao',
            'Siasi, Sulu',
            'Siaton, Negros Oriental',
            'Siay, Zamboanga Sibugay',
            'Siayan, Zamboanga Del Norte',
            'Sibagat, Agusan Del Sur',
            'Sibalom, Antique',
            'Sibonga, Cebu',
            'Sibuco, Zamboanga Del Norte',
            'Sibulan, Negros Oriental',
            'Sibunag, Guimaras',
            'Sibutad, Zamboanga Del Norte',
            'Sierra Bullones, Bohol',
            'Sigay, Ilocos Sur',
            'Sigma, Capiz',
            'Sikatuna, Bohol',
            'Silago, Southern Leyte',
            'Silang, Cavite',
            'Silay City, Negros Occidental',
            'Silvino Lobos, Northern Samar',
            ' Simunul, Tawi-tawi',
            'Sinacaban, Misamis Occidental',
            'Sinait, Ilocos Sur',
            'Sindangan, Zamboanga Del Norte',
            'Siniloan, Laguna',
            'Siocon, Zamboanga Del Norte',
            'Sipocot, Camarines Sur',
            'Siquijor, Siquijor',
            'Sirawai, Zamboanga Del Norte',
            'Siruma, Camarines Sur',
            'Sison, Pangasinan',
            'Sison, Surigao Del Norte',
            'Sitangkai, Tawi-tawi',
            'Socorro, Oriental Mindoro',
            'Socorro, Surigao Del Norte',
            'Sofronio Espanola, Palawan',
            'Sogod, Cebu',
            'Sogod, Southern Leyte',
            'Solana, Cagayan',
            'Solano, Nueva Vizcaya',
            'Solsona, Ilocos Norte',
            'Sominot (Don Mariano Marcos), Zamboanga Del Sur',
            'Sorsogon City, Sorsogon',
            'South Ubian, Tawi-tawi',
            'South Upi, Maguindanao',
            'Sual, Pangasinan',
            'Subic, Zambales',
            'Sudipen, La Union',
            'Sugbongcogon, Misamis Oriental',
            'Sugpon, Ilocos Sur',
            'Sulat, Eastern Samar',
            'Sulop, Davao Del Sur',
            'Sultan Kudarat, Maguindanao',
            'Sultan Mastura, Maguindanao',
            'Sultan Naga Dimaporo (Karomata, Lanao Del Norte',
            'Sultan Sa Barongis, Maguindanao',
            'Sumilao, Bukidnon',
            'Sumisip, Basilan',
            'Surallah, South Cotabato',
            'Surigao City (Capital), Surigao Del Norte',
            'Suyo, Ilocos Sur',
            'Tboli, South Cotabato',
            'Taal, Batangas',
            'Tabaco City, Albay',
            'Tabango, Leyte',
            'Tabina, Zamboanga Del Sur',
            'Tabogon, Cebu',
            'Tabontabon, Leyte',
            'Tabuelan, Cebu',
            'Tabuk (Capital), Kalinga',
            'Tacloban City, Leyte',
            'Tacurong City, Sultan Kudarat',
            'Tadian, Mountain Province',
            'Taft, Eastern Samar',
            'Tagana-An, Surigao Del Norte',
            'Tagapul-An, Western Samar',
            'Tagaytay City, Cavite',
            'Tagbilaran City, Bohol',
            'Tagbina, Surigao Del Sur',
            'Tagkawayan, Quezon',
            'Tago, Surigao Del Sur',
            'Tagoloan, Lanao Del Norte',
            'Tagoloan, Misamis Oriental',
            'Tagudin, Ilocos Sur',
            'Taguig, Metro Manila',
            'Tagum City (Capital), Davao Del Norte',
            'Talacogon, Agusan Del Sur',
            'Talaingod, Davao Del Norte',
            'Talakag, Bukidnon',
            'Talalora, Western Samar',
            'Talavera, Nueva Ecija',
            'Talayan, Maguindanao',
            'Talibon, Bohol',
            'Talipao, Sulu',
            'Talisay City, Cebu',
            'Talisay City, Negros Occidental',
            'Talisay, Batangas',
            'Talisay, Camarines Norte',
            'Talisayan, Misamis Oriental',
            'Talitay, Maguindanao',
            'Talugtug, Nueva Ecija',
            'Talusan, Zamboanga Sibugay',
            'Tambulig, Zamboanga Del Sur',
            'Tampakan, South Cotabato',
            'Tamparan, Lanao Del Sur',
            'Tampilisan, Zamboanga Del Norte',
            'Tanauan City, Batangas',
            'Tanauan, Leyte',
            'Tanay, Rizal',
            'Tandag (Capital), Surigao Del Sur',
            'Tandubas, Tawi-tawi',
            'Tangalan, Aklan',
            'Tangcal, Lanao Del Norte',
            'Tangub City, Misamis Occidental',
            'Tantangan, South Cotabato',
            'Tanudan, Kalinga',
            'Tanza, Cavite',
            'Tapaz, Capiz',
            'Tapul, Sulu',
            'Tarangan, Western Samar',
            'Tarlac City, Tarlac',
            'Tarragona, Davao Oriental',
            'Tayabas, Quezon',
            'Tayasan, Negros Oriental',
            'Taysan, Batangas',
            'Taytay, Palawan',
            'Taytay, Rizal',
            'Tayug, Pangasinan',
            'Tayum, Abra',
            'Teresa, Rizal',
            'Ternate, Cavite',
            'Tiaong, Quezon',
            'Tibiao, Antique',
            'Tigaon, Camarines Sur',
            'Tigbao, Zamboanga Del Sur',
            'Tigbauan, Iloilo',
            'Tinambac, Camarines Sur',
            'Tineg, Abra',
            'Tinglayan, Kalinga',
            'Tingloy, Batangas',
            'Tinoc, Ifugao',
            'Tipo-Tipo, Basilan',
            'Titay, Zamboanga Sibugay',
            'Tiwi, Albay',
            'Tobias Fornier (Dao), Antique',
            'Toboso, Negros Occidental',
            'Tolosa, Leyte',
            'Tomas Oppus, Southern Leyte',
            'Tongkil, Sulu',
            'Torrijos, Marinduque',
            'Trece Marteres City (Capital), Cavite',
            'Trento, Agusan Del Sur',
            'Trinidad, Bohol',
            'Tuao, Cagayan',
            'Tubajon, Surigao Del Norte',
            'Tubao, Benguet',
            'Tubao, La Union',
            'Tubaran, Lanao Del Sur',
            'Tubay, Agusan Del Norte',
            'Tubigon, Bohol',
            'Tublay, Benguet',
            'Tubo, Abra',
            'Tubod (Capital), Lanao Del Norte',
            'Tubod, Surigao Del Norte',
            'Tubungan, Iloilo',
            'Tuburan, Basilan',
            'Tuburan, Cebu',
            'Tudela, Cebu',
            'Tudela, Misamis Occidental',
            'Tuguegarao City, Cagayan',
            'Tukuran, Zamboanga Del Sur',
            'Tulunan, North Cotabato',
            'Tumauini, Isabela',
            'Tunga, Leyte',
            'Tungawan, Zamboanga Sibugay',
            'Tupi, South Cotabato',
            'Turtle Islands, Tawi-tawi',
            'Tuy, Batangas',
            'Ubay, Bohol',
            'Umingan, Pangasinan',
            'Unisan, Quezon',
            'Upi, Maguindanao',
            'Urbiztondo, Pangasinan',
            'Urdaneta City, Pangasinan',
            'Uson, Masbate',
            'Uyugan, Batanes',
            'Valderrama, Antique',
            'Valencia (Luzurrizga), Negros Oriental',
            'Valencia, Bohol',
            'Valenzuela City, Metro Manila',
            'Valladolid, Negros Occidental',
            'Vallehermoso, Negros Oriental',
            'Veruela, Agusan Del Sur',
            'Victoria, Laguna',
            'Victoria, Northern Samar',
            'Victoria, Oriental Mindoro',
            'Victoria, Tarlac',
            'Victorias City, Negros Occidental',
            'Viga, Catanduanes',
            'Vigan City (Capital), Ilocos Sur',
            'Villaba, Leyte',
            'Villanueva, Misamis Oriental',
            'Villareal, Western Samar',
            'Villasis, Pangasinan',
            'Villaverde, Nueva Vizcaya',
            'Vincenzo A. Sagun, Zamboanga Del Sur',
            'Vintar, Ilocos Norte',
            'Vinzons, Camarines Norte',
            'Virac, Catanduanes',
            'Zamboanga City, Zamboanga Del Sur',
            'Zamboanguita, Negros Oriental',
            'Zaragoza, Nueva Ecija',
            'Zarraga, Iloilo',
            'Zumarraga, Western Samar',
        ];

        foreach ($locations as $location) {
            Location::create(['name' => $location]);
        }
    }
}
